images:
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# image tag 수정
images:
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/cartservice
  newTag: 559dc28
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/currencyservice
  newTag: 9b91bc1
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/paymentservice
  newTag: 42d8fb2
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/productcatalogservice
  newTag: 9b91bc1
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/adservice
  newTag: 9b91bc1
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/recommendationservice
  newTag: 42d8fb2
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/emailservice
  newTag: 42d8fb2
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/frontend
  newTag: c8e923e
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/shippingservice
  newTag: 9b91bc1
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/checkoutservice
  newTag: 9b91bc1
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/loadgenerator
  newTag: 42d8fb2

# ingress 수정
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: frontend-ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: prod-frontend-ingress
      - op: replace
        path: /metadata/annotations/kubernetes.io~1ingress.global-static-ip-name
        value: ing-boutique-ip
      - op: replace
        path: /metadata/annotations/networking.gke.io~1managed-certificates
        value: ing-boutique-certificate
      - op: replace
        path: /spec/rules/0/host
        value: www.ing-boutique.shop

  - target:
      group: networking.gke.io
      version: v1
      kind: ManagedCertificate
      name: boutique-certificate
    patch: |-
      - op: replace
        path: /metadata/name
        value: ing-boutique-certificate
      - op: replace
        path: /spec/domains/0
        value: www.ing-boutique.shop
      - op: replace
        path: /spec/domains/1
        value: ing-boutique.shop

  - target:
      group: cloud.google.com
      version: v1
      kind: BackendConfig
      name: frontend-backend-config
    patch: |-
      - op: replace
        path: /spec/securityPolicy/name
        value: ing-boutique-security-policy

  - target:
      group: networking.gke.io
      version: v1beta1
      kind: FrontendConfig
      name: frontend-frontend-config
    patch: |-
      - op: replace
        path: /spec/sslPolicy
        value: ing-boutique-ssl-policy

# replica 수정
  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: adservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  # - target:
  #     group: autoscaling.gke.io
  #     version: v1beta1
  #     kind: MultidimPodAutoscaler
  #     name: cartservice-autoscaler
  #   patch: |-
  #     - op: replace
  #       path: /spec/constraints/global/minReplicas
  #       value: 4
  #     - op: replace
  #       path: /spec/constraints/global/maxReplicas
  #       value: 4
  #     - op: replace
  #       path: /spec/constraints/container/0/requests/minAllowed/memory
  #       value: "500Mi"
  #     - op: replace
  #       path: /spec/constraints/container/0/requests/maxAllowed/memory
  #       value: "1.5Gi"
  #     - op: replace
  #       path: /spec/goals/metrics/0/resource/target/averageUtilization
  #       value: 30

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: cartservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 4

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: cartservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "600m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "6000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "4Gi"

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: checkoutservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: currencyservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: emailservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: paymentservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: productcatalogservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: recommendationservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: shippingservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: frontend-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

# postgreSQL추가
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: cartservice
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "ALLOYDB_PRIMARY_IP", "value": "10.145.0.3" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "ALLOYDB_DATABASE_NAME", "value": "carts" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "ALLOYDB_TABLE_NAME", "value": "cart_items" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "ALLOYDB_SECRET_NAME", "value": "test-db-pw" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "PROJECT_ID", "value": "1081479304655" }
      - op: remove
        path: /spec/template/spec/containers/0/env/0
