---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  labels:
    app: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd
        image: asia-northeast3-docker.pkg.dev/protean-blend-398805/gcf-artifacts/my-image/argocd:42fab55
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd2-deployment
  labels:
    app: argocd2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd2
  template:
    metadata:
      labels:
        app: argocd2
    spec:
      containers:
      - name: argocd2
        image: asia-northeast3-docker.pkg.dev/protean-blend-398805/gcf-artifacts/my-image/argocd2:7aff2d0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  labels:
    app: argocd
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: argocd
