images:
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/cartservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/currencyservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/paymentservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/productcatalogservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/adservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/recommendationservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/emailservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/frontend
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/shippingservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/checkoutservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/loadgenerator
  newTag: 36a034f

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: frontend-ingress
    patch: |-
      - op: replace
        path: /metadata/annotations/kubernetes.io~1ingress.global-static-ip-name
        value: dev-boutique-ip
      - op: replace
        path: /metadata/annotations/networking.gke.io~1managed-certificates
        value: dev-boutique-certificate
      - op: replace
        path: /spec/rules/0/host
        value: www.dev-boutique.shop

  - target:
      group: networking.gke.io
      version: v1
      kind: ManagedCertificate
      name: boutique-certificate
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-boutique-certificate
      - op: replace
        path: /spec/domains/0
        value: www.dev-boutique.shop
      - op: replace
        path: /spec/domains/1
        value: dev-boutique.shop

  - target:
      group: cloud.google.com
      version: v1
      kind: BackendConfig
      name: frontend-backend-config
    patch: |-
      - op: replace
        path: /spec/securityPolicy/name
        value: dev-boutique-security-policy

  - target:
      group: networking.gke.io
      version: v1beta1
      kind: FrontendConfig
      name: frontend-frontend-config
    patch: |-
      - op: replace
        path: /spec/sslPolicy
        value: dev-boutique-ssl-policy

patchesStrategicMerge:
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: adservice
      spec:
        replicas: 5

  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: cartservice
      spec:
        replicas: 5

  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: checkoutservice
      spec:
        replicas: 5

  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: currencyservice
      spec:
        replicas: 5

  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: emailservice
      spec:
        replicas: 5

  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: paymentservice
      spec:
        replicas: 5

  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: productcatalogservice
      spec:
        replicas: 5

  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: recommendationservice
      spec:
        replicas: 5

  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: shippingservice
      spec:
        replicas: 5

  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: frontend
      spec:
        replicas: 5