images:
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# image tag 수정
images:
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/cartservice
  newTag: 08119c9
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/currencyservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/paymentservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/productcatalogservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/adservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/recommendationservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/emailservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/frontend
  newTag: 3009c9d
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/shippingservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/checkoutservice
  newTag: 5791e4b
- name: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/loadgenerator
  newTag: 36a034f

# ingress 수정
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: frontend-ingress
    patch: |-
      - op: replace
        path: /metadata/annotations/kubernetes.io~1ingress.global-static-ip-name
        value: dev-boutique-ip
      - op: replace
        path: /metadata/annotations/networking.gke.io~1managed-certificates
        value: dev-boutique-certificate
      - op: replace
        path: /spec/rules/0/host
        value: www.dev-boutique.shop

  - target:
      group: networking.gke.io
      version: v1
      kind: ManagedCertificate
      name: boutique-certificate
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-boutique-certificate
      - op: replace
        path: /spec/domains/0
        value: www.dev-boutique.shop
      - op: replace
        path: /spec/domains/1
        value: dev-boutique.shop

  - target:
      group: cloud.google.com
      version: v1
      kind: BackendConfig
      name: frontend-backend-config
    patch: |-
      - op: replace
        path: /spec/securityPolicy/name
        value: dev-boutique-security-policy

  - target:
      group: networking.gke.io
      version: v1beta1
      kind: FrontendConfig
      name: frontend-frontend-config
    patch: |-
      - op: replace
        path: /spec/sslPolicy
        value: dev-boutique-ssl-policy

# replica 수정
  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: adservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: cartservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: checkoutservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: currencyservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: emailservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: paymentservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: productcatalogservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: recommendationservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: shippingservice-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: frontend-autoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2

# postgreSQL추가
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: cartservice
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "ALLOYDB_PRIMARY_IP", "value": "10.46.176.3" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "ALLOYDB_DATABASE_NAME", "value": "carts" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "ALLOYDB_TABLE_NAME", "value": "cart_items" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "ALLOYDB_SECRET_NAME", "value": "test-db-pw" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { "name": "PROJECT_ID", "value": "yoondaegyoung-01-400304" }
      - op: remove
        path: /spec/template/spec/containers/0/env/0