apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  strategy:
    blueGreen:
      activeService: currencyservice-active
      autoPromotionEnabled: true
      previewService: currencyservice-preview
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - env:
        - name: PORT
          value: '7000'
        - name: DISABLE_PROFILER
          value: '1'
        image: asia-docker.pkg.dev/yoondaegyoung-01-400304/gcf-artifacts/boutique-image/currencyservice:0381ee5
        livenessProbe:
          grpc:
            port: 7000
        name: server
        ports:
        - containerPort: 7000
          name: grpc
        readinessProbe:
          grpc:
            port: 7000
        resources:
          limits:
            cpu: 150m
            memory: 64Mi
          requests:
            cpu: 150m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      nodeSelector:
        cloud.google.com/gke-nodepool: boutique
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice-active
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: currencyservice
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice-preview
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: currencyservice
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: currencyservice-autoscaler
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: currencyservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50