apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-backend-config
spec:
  securityPolicy:
    name: boutique-security-policy
  logging:
    enable: true
    sampleRate: 0.5
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 50
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-frontend-config
spec:
  sslPolicy: boutique-ssl-policy
  redirectToHttps:
    enabled: true
    responseCodeName: ""
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: boutique-ip
    networking.gke.io/managed-certificates: boutique-certificate
    networking.gke.io/v1beta1.FrontendConfig: frontend-frontend-config
spec:
  # defaultBackend:
  #   service:
  #     name: frontend-active
  #     port:
  #       number: 80
  rules:
  - host: "www.2280.store"
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-active
            port:
              number: 80
  - host: "www.2280.store"
    http:
      paths:
      - path: /argo
        pathType: Prefix
        backend:
          service:
            name: argocd-server-external
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: boutique-certificate
spec:
  domains:
    - www.2280.store
    - 2280.store