apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  annotations:
    iam.gke.io/gcp-service-account: postdb-user-sa@yoondaegyoung-01-400304.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boutique-sa
  annotations:
    iam.gke.io/gcp-service-account: wlid-boutique-sa@yoondaegyoung-01-400304.iam.gserviceaccount.com
